### PR TITLE
label text swap

### PR DESCRIPTION
**Pull request by MiTo0o**

### CODE REVIEW

**Comment by MiTo0o** [comment]
closes #1

**Comment by MiTo0o** [comment]
not exactly sure if this is what you want? Also not sure of how to swap parameters of a function call easily.

**Comment by dashroshan** [comment]
This won't work the way it is now.

Use `req.query.swap || "0"` to avoid the code crashing when the swap parameter is not used in the query. This returns `"0"` in such a case. Now if it is "0" call the svgBadge function the way it original was. If it is "1" put label in place of  visits, and visits in place of label in the function call.

**Comment by dashroshan** [comment]
Looks good now, but you mistyped req as eq

**Comment by MiTo0o** [comment]
@roshan1337d I used a ternary statement to assign the svg badge.....I was wondering if there's a better way to do way than I did it?

**Comment by dashroshan** [comment]
Its all good, nice work 👍

**Comment by MiTo0o** [comment]
Thank you! :D

**Pull request merged**
